name: Setup Bun Environment
description: Bootstraps Bun and dependencies
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun Dependencies
      uses: actions/cache@v6
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install Dependencies
      run: bun install --frozen-lockfile
      shell: bash
