name: Centralized Checkout
description: Wrapper for actions/checkout@v7 to centralize version management

inputs:
  fetch-depth:
    description: "Number of commits to fetch"
    required: false
    default: "1"
  token:
    description: "Personal Access Token"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Run Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
