name: CI (Pull Request Verification)

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
      - "LICENSE"

jobs:
  integration:
    uses: ./.github/workflows/integration.yml
