name: CI (Pull Request Verification)

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
      - "LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  integration:
    uses: ./.github/workflows/integration.yml
    secrets: inherit
