name: CI

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - ".gitignore"
      - "LICENSE"
      - ".vscode/**"

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: "Quality Gate"
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/integration.yml
    secrets: inherit
